spring:
  application:
    name: security-service
  datasource:
    url: jdbc:mysql://localhost:23306/security
    username: security
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${CLIENT_ID}
            client-secret: ${CLIENT_SECRET}
            scope:
              - email
              - profile

logging:
  level:
    org:
      jooq:
        tools:
          LoggerListener: debug
server:
  port: 18080

